---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.8"

reference:
  fasta: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.fasta"
  fai: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.fasta.fai"
  dict: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.dict"
  amb: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta.amb"
  ann: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta.ann"
  bwt: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta.bwt"
  pac: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta.pac"
  sa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta.sa"
  design_bed: "/projects/wp2/nobackup/CGU_2022_12_BCR-ABL1/Bin/bcr_abl_pipeline/config/bcr_abl1.bed"
  skip_chrs:
      - "chr1"
      - "chr2"
      - "chr3"
      - "chr4"
      - "chr5"
      - "chr6"
      - "chr7"
      - "chr8"
      - "chr10"
      - "chr11"
      - "chr12"
      - "chr13"
      - "chr14"
      - "chr15"
      - "chr16"
      - "chr17"
      - "chr18"
      - "chr19"
      - "chr20"
      - "chr21"
      - "chrX"
      - "chrY"
      - "chrM"

arriba:
  container: "docker://hydragenetics/arriba:2.3.0"
  assembly: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.fasta"
  blacklist: "/data/ref_data/arriba/arriba_v2.3.0/database/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"
  gtf: "/data/ref_genomes/hg19/gtf/hg19.refGene.gtf"
  extra: "-p /data/ref_data/arriba/arriba_v2.3.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3 -k /data/ref_data/arriba/arriba_v2.3.0/database/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"

arriba_draw_fusion:
  container: "docker://hydragenetics/arriba:2.3.0"
  cytobands: "/data/ref_data/arriba/arriba_v2.3.0/database/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv"
  gtf: "/data/ref_genomes/hg19/gtf/hg19.refGene.gtf"
  protein_domains: "/data/ref_data/arriba/arriba_v2.3.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3"

fastp_pe:
   container: "docker://hydragenetics/fastp:0.20.1"
   extra: "-x "

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

fusioncatcher:
  container: "docker://hydragenetics/fusioncatcher:1.33"
  genome_path: "/data/ref_data/fusioncatcher/human_v102/human_v102/"

gatk_mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--max-reads-per-alignment-start 0 --recover-all-dangling-branches true"
  bed_files:
    branford: "/projects/wp2/nobackup/CGU_2022_12_BCR-ABL1/Bin/bcr_abl_pipeline/config/branford_bcr-abl1_positions.bed"

gatk_mutect2_filter:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  extra: "--max-alt-allele-count 3 --max-events-in-region 20"

gatk_mutect2_merge_stats:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  design_bed: "/projects/wp2/nobackup/CGU_2022_12_BCR-ABL1/Bin/bcr_abl_pipeline/config/bcr_abl1.bed"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    RNA:
      included_unit_types: ['R']
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{barcode}_{type}_fastp.json"
        - "alignment/star/{sample}_{type}.Log.final.out"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed/{sample}_{type}.regions.bed.gz"
        - "qc/mosdepth_bed/{sample}_{type}.regions.bed.gz.csi"



rseqc_gene_body_coverage:
  bed: "/projects/wp2/nobackup/CGU_2022_12_BCR-ABL1/Bin/bcr_abl_pipeline/config/bcr_abl1.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

rseqc_inner_distance:
  bed: "/projects/wp2/nobackup/CGU_2022_12_BCR-ABL1/Bin/bcr_abl_pipeline/config/bcr_abl1.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

star:
  container: "docker://hydragenetics/star:2.7.10a"
  genome_index: "/data/ref_data/star/v2.7.10a_hg19/"
  extra: "--outSAMmapqUnique 250 --quantMode GeneCounts --sjdbGTFfile /data/ref_genomes/hg19/gtf/hg19.refGene.gtf --outSAMtype BAM SortedByCoordinate --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3"

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: "/data/ref_data/star-fusion/GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/"

trimmer_software: "fastp_pe"

vt_decompose:
  container: "docker://hydragenetics/vt:2015.11.10"

vt_normalize:
  container: "docker://hydragenetics/vt:2015.11.10"
