directory: ./Results

files:
  - name: vcf file
    input: "snv_indels/pisces/{sample}_R.merged.vcf.gz"
    output: "{sample}_R/{sample}_R.merged.vcf.gz"

  - name: tbi file
    input: null
    output: "{sample}_R/{sample}_R.merged.vcf.gz.tbi"

  - name: config file
    input: config.yaml
    output: "{sample}_R/{sample}_R.config.yaml"

  - name: reference tsv-file
    input: references/create_background_file/background_panel.tsv
    output: background_panel.tsv
