---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 3072
  partition: core

arriba:
  mem_mb: 46080
  threads: 5
  time: "72:00:00"

dotnet_pisces:
  threads: 10

fastp_pe:
  mem_mb: 73728
  threads: 8

fusioncatcher:
  mem_mb: 92160
  threads: 10
  time: "96:00:00"

mosdepth_bed:
  mem_mb: 36864
  threads: 4

sortmerna:
  mem_mb: 73728
  threads: 8

spring:
  mem_mb: 73728
  threads: 8

star:
  mem_mb: 73728
  threads: 8

star_fusion:
  mem_mb: 46080
  threads: 5
  time: "72:00:00"
